### ISSUE TITLE
Add Windows 10 Accounts extension

### ISSUE THREAD

**Issue by trs80** [campioneducation/myconnect-release-electron#1]
Hi,

Could you include the [Windows 10 Accounts](https://chrome.google.com/webstore/detail/windows-10-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji?hl=en) extension in your build? This will allow us to use Azure AD Conditional Access to authenticate teachers using their device. https://www.electronjs.org/docs/latest/api/extensions has some instructions on including extensions in Electron.

Thanks,

James

**Comment by acandylevey** [comment]
Hi James,

Thanks for raising this, I can see how this would be helpful to a lot of schools around the country. 
We've had a chat internally and someone will reach out to you with some more information to have a discussion. 

We always recommend that any issues or suggestions you've got either be raised with our Support team (Which can be done via the chat within MyConnect), or through your account manager.

Just letting you know that, we'll be turning off issues and some of the other functionality on Github as we don't monitor it, so anything raised is likely to go missed.

Alexander
